// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iX1qkSjgNN2uqWdAcYpiJf
// Component: 4kLu1vpnA8Ps
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SectionHeading from "../../SectionHeading"; // plasmic-import: daEkghagFJN8/component
import Columns from "../../Columns"; // plasmic-import: y4i2wU8BJ8FX/component
import ListItem from "../../ListItem"; // plasmic-import: -oP-bZni7oo/component
import YouTube from ""; // plasmic-import: xdkygkmsYFc/codeComponent
import { GoogleMap } from ""; // plasmic-import: VaUi3lG05rQ/codeComponent
import { MuiSelect } from ""; // plasmic-import: BB4xeSsZJNiI/codeComponent
import { ButtonGroup } from ""; // plasmic-import: _cg0mlGay8sR/codeComponent
import { Button } from ""; // plasmic-import: zswNPRkGYstc/codeComponent
import { Slider } from ""; // plasmic-import: 4pwS_2JDasK/codeComponent
import { Menu } from ""; // plasmic-import: TY1KqIMrBeL/codeComponent
import MenuItem from ""; // plasmic-import: xrjSTPEpui7/codeComponent
import { Alert } from ""; // plasmic-import: TlJlteHapcE/codeComponent
import { Collapse } from ""; // plasmic-import: N2WavU1KETc/codeComponent
import CollapsePanel from ""; // plasmic-import: 5UXgNi8zO1-/codeComponent
import { ArwesCard } from ""; // plasmic-import: -Km-19NqAtZg/codeComponent
import { Text } from ""; // plasmic-import: RZku6gL1-ovo/codeComponent
import { Figure } from ""; // plasmic-import: hUDSAkEOYTbG/codeComponent
import { ProductCollection } from "../../../../ProductComponents"; // plasmic-import: h-gCoP3zijN7/codeComponent
import { ProductImage } from ""; // plasmic-import: POaPMHxM7_o-/codeComponent
import { ProductPrice } from ""; // plasmic-import: AdGGulWXqkaR/codeComponent
import { ProductTitle } from ""; // plasmic-import: KxbSPhL6IBr_/codeComponent
import { CmsGallery } from ""; // plasmic-import: gj3FiRMykZdh/codeComponent
import { CmsItemField } from ""; // plasmic-import: 2EsAnxrKsacQ/codeComponent
import { Reveal } from ""; // plasmic-import: tiX1fiAOq4bb/codeComponent
import { Tilt } from ""; // plasmic-import: eMvuEZPP0RFt/codeComponent
import { ParallaxWrapper } from ""; // plasmic-import: JbAFDIxR5T6r/codeComponent
import { Embed } from ""; // plasmic-import: 5cagPN_uwBzZ/codeComponent
import ColoredSection from "../../ColoredSection"; // plasmic-import: Z-b5cx4Z8FRT/component
import LinkButton from "../../LinkButton"; // plasmic-import: 65vBthjiMfiU/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: puP8FUTSqJAM/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_code_component_examples.module.css"; // plasmic-import: iX1qkSjgNN2uqWdAcYpiJf/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: 4kLu1vpnA8Ps/css

import PlasmicLogoIcon from "./icons/PlasmicIcon__PlasmicLogo"; // plasmic-import: 47n026-Ftuh5/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: NL-51K78_IY4/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: -ZpF1G2OFzRe/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: Ptf7KHIQp4Qy/icon
import Icon8Icon from "../plasmic_kit_website_components/icons/PlasmicIcon__Icon8"; // plasmic-import: f4GO4W3yZm/icon
import imageWo3RawwxIqnd from "./images/image.png"; // plasmic-import: wo3RawwxIQND/picture
import image15TBnLlg7N52Rn from "./images/image15.png"; // plasmic-import: tBnLLG7n52RN/picture
import image6BZy1EJvTxz8V from "./images/image6.png"; // plasmic-import: bZY1eJvTxz8v/picture
import image5YFsTPi6WzJiH from "./images/image5.png"; // plasmic-import: YFsTPi6WzJiH/picture
import image7Qebey7WcP8Ki from "./images/image7.png"; // plasmic-import: QEBEY7wcP8Ki/picture
import image8OsNbT5LMrWcp from "./images/image8.png"; // plasmic-import: osNbT5lMRWcp/picture
import image14Zxn1TasF4EtG from "./images/image14.svg"; // plasmic-import: zxn1TasF4etG/picture

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  sectionHeading?: p.Flex<typeof SectionHeading>;
  columns?: p.Flex<typeof Columns>;
  arwesCard?: p.Flex<typeof ArwesCard>;
  h1?: p.Flex<"h1">;
  arwesFigure?: p.Flex<typeof Figure>;
  cmsGallery?: p.Flex<typeof CmsGallery>;
  reveal?: p.Flex<typeof Reveal>;
  tilt?: p.Flex<typeof Tilt>;
  embed?: p.Flex<typeof Embed>;
  coloredSection?: p.Flex<typeof ColoredSection>;
  linkButton?: p.Flex<typeof LinkButton>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.freeBox__xfyPb)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___0Warq)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__at8R)}
              >
                <a
                  className={classNames(defaultcss.a, sty.link__wg3D0)}
                  href={"https://www.plasmic.app" as const}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__tq07)}
                    src={imageWo3RawwxIqnd}
                  />
                </a>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__nd2HU)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__mRloP
                  )}
                >
                  {"Page builder, meet code components."}
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__riiad)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__n7SHs
                    )}
                  >
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                    >
                      <React.Fragment>{"Introducing "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Plasmic 2.0"}
                      </span>
                      <React.Fragment>
                        {
                          ": the web design tool that integrates seamlessly with your codebase and lets you drag-and-drop your real production React components."
                        }
                      </React.Fragment>
                    </span>
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__dRqM4
                    )}
                  >
                    {
                      "Empower your team with your design system, interactive components, production data, and much more."
                    }
                  </div>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__eMIkh)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__xIe)}
                  src={image15TBnLlg7N52Rn}
                />

                <a
                  className={classNames(
                    defaultcss.a,
                    defaultcss.__wab_text,
                    sty.link__qKc1A
                  )}
                  href={"https://plasmic.app/proj/code-components" as const}
                  target={"_blank" as const}
                >
                  {"Edit this page in Plasmic!"}
                </a>
              </p.Stack>
            </p.Stack>
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.freeBox___47WeE)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__zgIme)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__fybfQ)}
              >
                <SectionHeading
                  data-plasmic-name={"sectionHeading"}
                  data-plasmic-override={overrides.sectionHeading}
                  className={classNames("__wab_instance", sty.sectionHeading)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___5AksB
                  )}
                >
                  {
                    "Tap into the full universe of open-source npm libraries. Or expose components from your own codebase."
                  }
                </div>
              </p.Stack>

              <Columns
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames("__wab_instance", sty.columns)}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___6W613)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___5OTF)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___8Kc17)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___3VMcq)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__mbC
                      )}
                    >
                      {"Bring any design system."}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__uNqH
                      )}
                    >
                      {
                        "Use your own design system, or use off-the-shelf libraries complete with all the theming and customizations you've applied in your codebase. Seamlessly interweave Plasmic-designed content and code components."
                      }
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__bZk9C
                      )}
                    >
                      {"Roboto"}
                    </div>
                  </p.Stack>
                </p.Stack>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__jxPok
                      )}
                    >
                      {"@material-ui/core"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__ttpm1)}
                  title={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___3PnUl
                      )}
                    >
                      {"Material UI"}
                    </div>
                  }
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___5Fiyb)}
                  >
                    <MuiSelect
                      className={classNames(
                        "__wab_instance",
                        sty.muiSelect___0MnUl
                      )}
                      label={"Delivery method" as const}
                      options={[
                        { value: "standard", label: "Standard Shipping" },
                        { value: "expedited", label: "Expedited Shipping" },
                        { value: "sameday", label: "Same-Day Delivery" },
                        { value: "pickup", label: "Scheduled Pickup" }
                      ]}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__ea8Ch)}
                    >
                      <ButtonGroup
                        className={classNames(
                          "__wab_instance",
                          sty.muiButtonGroup__tsk3C
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton__o36E8
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.text__cs6Sl
                            )}
                          >
                            {"md"}
                          </div>
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton__bzMk0
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.text__mJk0V
                            )}
                          >
                            {"lg"}
                          </div>
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton__xL2Wj
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.text__xMov1
                            )}
                          >
                            {"xl"}
                          </div>
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton__u8Hu2
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.text___2TXg7
                            )}
                          >
                            {"xxl"}
                          </div>
                        </Button>
                      </ButtonGroup>
                    </p.Stack>
                  </p.Stack>
                </ListItem>

                {false ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__nfas8)}
                  >
                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__zfth8
                          )}
                        >
                          {"@material-ui/core"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__sdhGr
                      )}
                      title={"Material UI Select"}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__n7IYp
                        )}
                      >
                        <MuiSelect
                          className={classNames(
                            "__wab_instance",
                            sty.muiSelect__lmTjg
                          )}
                          label={"Delivery method" as const}
                          options={[
                            { value: "standard", label: "Standard Shipping" },
                            { value: "expedited", label: "Expedited Shipping" },
                            { value: "sameday", label: "Same-Day Delivery" },
                            { value: "pickup", label: "Scheduled Pickup" }
                          ]}
                        />
                      </p.Stack>
                    </ListItem>

                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__axYgb
                          )}
                        >
                          {"@material-ui/core"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__zs4Ue
                      )}
                      title={"Material UI Button Group"}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__ombLy
                        )}
                      >
                        <ButtonGroup
                          className={classNames(
                            "__wab_instance",
                            sty.muiButtonGroup__zcnZh
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton___4GTeN
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__mpmh
                              )}
                            >
                              {"md"}
                            </div>
                          </Button>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton___1Ly1K
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text___1Vgkl
                              )}
                            >
                              {"lg"}
                            </div>
                          </Button>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton___10Pnl
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text___1I3C
                              )}
                            >
                              {"xl"}
                            </div>
                          </Button>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton___0GG1E
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__wkFTm
                              )}
                            >
                              {"xxl"}
                            </div>
                          </Button>
                        </ButtonGroup>
                      </p.Stack>
                    </ListItem>
                  </p.Stack>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__sGfRa)}
                  >
                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__hBn4Y
                          )}
                        >
                          {"antd"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__bZWp8
                      )}
                      title={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__uas4J
                          )}
                        >
                          {"Ant Design"}
                        </div>
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__za1Jy
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__opmdf
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__s5292
                            )}
                          >
                            <Slider
                              className={classNames(
                                "__wab_instance",
                                sty.slider__lnEf
                              )}
                              range={true}
                            />

                            <Menu
                              className={classNames(
                                "__wab_instance",
                                sty.menu__f5PoP
                              )}
                              defaultSelectedKeys={["opt3"]}
                            >
                              <MenuItem
                                className={classNames(
                                  "__wab_instance",
                                  sty.menuItem___8AP1K
                                )}
                                key={"opt1" as const}
                              >
                                {"Home"}
                              </MenuItem>

                              <MenuItem
                                className={classNames(
                                  "__wab_instance",
                                  sty.menuItem__bY9J
                                )}
                                key={"opt2" as const}
                              >
                                {"Features"}
                              </MenuItem>

                              <MenuItem
                                className={classNames(
                                  "__wab_instance",
                                  sty.menuItem___1Ux2I
                                )}
                                key={"opt3" as const}
                              >
                                {"Case studies"}
                              </MenuItem>
                            </Menu>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox___8EdQh
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                sty.freeBox___0Spt1
                              )}
                            >
                              <Alert
                                className={classNames(
                                  "__wab_instance",
                                  sty.alert__jnpt2
                                )}
                                description={
                                  <div
                                    className={classNames(
                                      defaultcss.all,
                                      sty.freeBox__oEwGa
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.text__uwhv
                                      )}
                                    >
                                      {"Thank you for your order! "}
                                    </div>

                                    <PlasmicLogoIcon
                                      className={classNames(
                                        defaultcss.all,
                                        sty.svg___26DyF
                                      )}
                                      role={"img"}
                                    />
                                  </div>
                                }
                                message={"Purchase complete" as const}
                                showIcon={true}
                                type={"success" as const}
                              />

                              <Alert
                                className={classNames(
                                  "__wab_instance",
                                  sty.alert__wWeT
                                )}
                                description={"Please fill all required fields."}
                                message={"Error submitting form" as const}
                                showIcon={true}
                                type={"error" as const}
                              />
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                sty.freeBox___81NRk
                              )}
                            >
                              <Collapse
                                className={classNames(
                                  "__wab_instance",
                                  sty.collapse__bTs1Y
                                )}
                                defaultActiveKey={["1"]}
                              >
                                <CollapsePanel
                                  className={classNames(
                                    "__wab_instance",
                                    sty.collapsePanel__n7NdY
                                  )}
                                  header={"Shipping" as const}
                                  key={"1" as const}
                                >
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      defaultcss.all,
                                      sty.freeBox__q8MCy
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.text__dr6Ve
                                      )}
                                    >
                                      {"Standard shipping"}
                                    </div>

                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.text__uuK1
                                      )}
                                    >
                                      {"2 South Park\nSan Francisco, CA 94107"}
                                    </div>

                                    <a
                                      className={classNames(
                                        defaultcss.a,
                                        defaultcss.__wab_text,
                                        sty.link___13Ljh
                                      )}
                                      href={"#" as const}
                                    >
                                      {"Change"}
                                    </a>
                                  </p.Stack>
                                </CollapsePanel>

                                <CollapsePanel
                                  className={classNames(
                                    "__wab_instance",
                                    sty.collapsePanel__lIuca
                                  )}
                                  header={"Payment method" as const}
                                  key={"2" as const}
                                >
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      defaultcss.all,
                                      sty.freeBox__eQmwT
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.text__zbaH
                                      )}
                                    >
                                      {"Using gift card balance."}
                                    </div>

                                    <a
                                      className={classNames(
                                        defaultcss.a,
                                        defaultcss.__wab_text,
                                        sty.link__yBncr
                                      )}
                                      href={"#" as const}
                                    >
                                      {"Change"}
                                    </a>
                                  </p.Stack>
                                </CollapsePanel>
                              </Collapse>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </ListItem>
                  </p.Stack>
                ) : null}
                {false ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___3V0Yv)}
                  >
                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___3Qp5X
                          )}
                        >
                          {"antd"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__c4MPf
                      )}
                      title={"Ant Slider"}
                    >
                      <Slider
                        className={classNames(
                          "__wab_instance",
                          sty.slider__hMout
                        )}
                        range={true}
                      />
                    </ListItem>

                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__b7FsP
                          )}
                        >
                          {"antd"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__rSdV
                      )}
                      title={"Ant Menu"}
                    >
                      <Menu
                        className={classNames("__wab_instance", sty.menu__aqKJ)}
                      >
                        <MenuItem
                          className={classNames(
                            "__wab_instance",
                            sty.menuItem__phwrs
                          )}
                          key={"opt1" as const}
                        >
                          {"Home"}
                        </MenuItem>

                        <MenuItem
                          className={classNames(
                            "__wab_instance",
                            sty.menuItem__ntFtJ
                          )}
                          key={"opt2" as const}
                        >
                          {"Features"}
                        </MenuItem>

                        <MenuItem
                          className={classNames(
                            "__wab_instance",
                            sty.menuItem__tJeEq
                          )}
                          key={"opt3" as const}
                        >
                          {"Case studies"}
                        </MenuItem>
                      </Menu>
                    </ListItem>
                  </p.Stack>
                ) : null}
                {false ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__uXtMc)}
                  >
                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__df8Ts
                          )}
                        >
                          {"antd"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__aSmrx
                      )}
                      title={"Ant Alert"}
                    >
                      <Alert
                        className={classNames(
                          "__wab_instance",
                          sty.alert__jqOPr
                        )}
                        description={
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__zdsLu
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text___4Vbxe
                              )}
                            >
                              {"Thank you for your order! "}
                            </div>

                            <PlasmicLogoIcon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__qOrMt
                              )}
                              role={"img"}
                            />
                          </div>
                        }
                        message={"Purchase complete" as const}
                        showIcon={true}
                      />

                      <Alert
                        className={classNames(
                          "__wab_instance",
                          sty.alert__mAx7G
                        )}
                        description={"Please fill all required fields."}
                        message={"Error submitting form" as const}
                        showIcon={true}
                      />
                    </ListItem>

                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__iHraM
                          )}
                        >
                          {"antd"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__lY9ZP
                      )}
                      title={"Ant Collapse"}
                    >
                      <Collapse
                        className={classNames(
                          "__wab_instance",
                          sty.collapse___1ByZg
                        )}
                      >
                        <CollapsePanel
                          className={classNames(
                            "__wab_instance",
                            sty.collapsePanel___761Gx
                          )}
                          header={"Shipping" as const}
                          key={"1" as const}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__qw4Pz
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__h15Pt
                              )}
                            >
                              {"Standard shipping"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__amcIr
                              )}
                            >
                              {"2 South Park\nSan Francisco, CA 94107"}
                            </div>

                            <a
                              className={classNames(
                                defaultcss.a,
                                defaultcss.__wab_text,
                                sty.link__bUlTy
                              )}
                              href={"#" as const}
                            >
                              {"Change"}
                            </a>
                          </p.Stack>
                        </CollapsePanel>

                        <CollapsePanel
                          className={classNames(
                            "__wab_instance",
                            sty.collapsePanel__w3Vbz
                          )}
                          header={"Payment method" as const}
                          key={"2" as const}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__wnrE
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__cJi5K
                              )}
                            >
                              {"Using gift card balance."}
                            </div>

                            <a
                              className={classNames(
                                defaultcss.a,
                                defaultcss.__wab_text,
                                sty.link___7Efot
                              )}
                              href={"#" as const}
                            >
                              {"Change"}
                            </a>
                          </p.Stack>
                        </CollapsePanel>
                      </Collapse>
                    </ListItem>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.freeBox__f7ROl)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__xkrgW)}
                >
                  <ListItem
                    _package={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__lYdiF
                        )}
                      >
                        {"@arwes/core"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__dmAcq
                    )}
                    title={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__cRvHv
                        )}
                      >
                        {"Arwes Card"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__ynYb9)}
                    >
                      <ArwesCard
                        data-plasmic-name={"arwesCard"}
                        data-plasmic-override={overrides.arwesCard}
                        caption={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.text__mbNOo
                            )}
                          >
                            {"Photo of the Orion nebula taken by Hubble."}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.arwesCard)}
                        title={
                          true ? (
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__kIium
                              )}
                            >
                              {"Nebula"}
                            </div>
                          ) : null
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__zKsLg
                          )}
                        >
                          <Text
                            as={"h1" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.arwesText__fLwTr
                            )}
                          >
                            {true ? (
                              <h1
                                data-plasmic-name={"h1"}
                                data-plasmic-override={overrides.h1}
                                className={classNames(
                                  defaultcss.h1,
                                  defaultcss.__wab_text,
                                  sty.h1
                                )}
                              >
                                {"NEBULA"}
                              </h1>
                            ) : null}
                          </Text>

                          <Text
                            as={"p" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.arwesText__mfIlL
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__qlwxb
                              )}
                            >
                              {
                                "A nebula is an interstellar cloud of dust, hydrogen, helium and other ionized gases. Originally, the term was used to describe any diffused astronomical object, including galaxies beyond the Milky Way."
                              }
                            </div>
                          </Text>

                          <Figure
                            data-plasmic-name={"arwesFigure"}
                            data-plasmic-override={overrides.arwesFigure}
                            alt={"Orion" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.arwesFigure
                            )}
                            src={
                              "https://playground.arwes.dev/assets/images/wallpaper.jpg" as const
                            }
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__ltv0N
                              )}
                            >
                              {"Photo of the Orion nebula taken by Hubble."}
                            </div>
                          </Figure>
                        </div>
                      </ArwesCard>
                    </div>
                  </ListItem>
                </p.Stack>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__tWbU2)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__efxqo)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__jnCp1
                  )}
                >
                  {"Access your real production data."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___5Uk
                  )}
                >
                  {
                    "Bring components of any complexity—components that fetch data, use application/session state, and more."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__qSnYy)}
              >
                <ListItem
                  _package={null}
                  className={classNames("__wab_instance", sty.listItem__umXiP)}
                  title={
                    "Data from Shopify product catalog (via Storefront GraphQL API)"
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hrIds
                    )}
                  >
                    {"SUMMER COLLECTION"}
                  </div>

                  <ProductCollection
                    className={classNames(
                      "__wab_instance",
                      sty.productCollection__e6NLi
                    )}
                    collectionHandle={"summer-collection" as const}
                    columnGap={16 as const}
                    columns={4 as const}
                    rowGap={16 as const}
                    scroller={true}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__ljWw)}
                    >
                      <ProductImage
                        className={classNames(
                          "__wab_instance",
                          sty.productImage__mgZdE
                        )}
                      />

                      <ProductPrice
                        className={classNames(
                          "__wab_instance",
                          sty.productPrice__qNBoq
                        )}
                      />

                      <ProductTitle
                        className={classNames(
                          "__wab_instance",
                          sty.productTitle__kvub0
                        )}
                      />
                    </p.Stack>
                  </ProductCollection>
                </ListItem>
              </p.Stack>

              <ListItem
                _package={null}
                className={classNames("__wab_instance", sty.listItem__l7JQ0)}
                title={"Data from Contentful CMS (via REST API)"}
              >
                <div className={classNames(defaultcss.all, sty.freeBox___1OvD)}>
                  <CmsGallery
                    data-plasmic-name={"cmsGallery"}
                    data-plasmic-override={overrides.cmsGallery}
                    className={classNames("__wab_instance", sty.cmsGallery)}
                    columnGap={16 as const}
                    columns={4 as const}
                    rowGap={16 as const}
                    scroller={true}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___8GFrN
                      )}
                    >
                      <CmsItemField
                        className={classNames(
                          "__wab_instance",
                          sty.cmsItemField__m3GAj
                        )}
                        field={"photo" as const}
                      />

                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__yb5Ss
                        )}
                      >
                        <CmsItemField
                          className={classNames(
                            "__wab_instance",
                            sty.cmsItemField__sSpSk
                          )}
                          field={"title" as const}
                        />
                      </div>
                    </div>
                  </CmsGallery>
                </div>
              </ListItem>

              <ListItem
                _package={null}
                className={classNames("__wab_instance", sty.listItem__shLp8)}
                title={"Data from Shopify product catalog (as a CSS grid)"}
              >
                <div className={classNames(defaultcss.all, sty.freeBox__iyPz0)}>
                  <ProductCollection
                    className={classNames(
                      "__wab_instance",
                      sty.productCollection__wDr7Y
                    )}
                    columnGap={16 as const}
                    columns={4 as const}
                    rowGap={16 as const}
                  >
                    <ProductTitle
                      className={classNames(
                        "__wab_instance",
                        sty.productTitle___7PoFw
                      )}
                    />

                    <ProductPrice
                      className={classNames(
                        "__wab_instance",
                        sty.productPrice__z41Nt
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___3NLb
                      )}
                    >
                      {"Hello"}
                    </div>

                    <ProductImage
                      className={classNames(
                        "__wab_instance",
                        sty.productImage__lsGdG
                      )}
                    />
                  </ProductCollection>
                </div>

                <ProductCollection
                  className={classNames(
                    "__wab_instance",
                    sty.productCollection__g8LkN
                  )}
                  collectionHandle={"casual-things" as const}
                  columnGap={16 as const}
                  columns={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? (2 as const)
                      : (4 as const)
                  }
                  count={8 as const}
                  rowGap={16 as const}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___1JW21)}
                  >
                    <ProductImage
                      className={classNames(
                        "__wab_instance",
                        sty.productImage__yydIu
                      )}
                    />

                    <ProductPrice
                      className={classNames(
                        "__wab_instance",
                        sty.productPrice__pDj9
                      )}
                    />

                    <ProductTitle
                      className={classNames(
                        "__wab_instance",
                        sty.productTitle__yRDbU
                      )}
                    />
                  </p.Stack>
                </ProductCollection>
              </ListItem>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox__xwKwF)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__b2XGz)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__pi1Lr)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vCm87
                    )}
                  >
                    {"Extend Plasmic with any interaction."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ryS1K
                    )}
                  >
                    {
                      "You can introduce some very general-purpose building blocks that extend Plasmic's feature set."
                    }
                  </div>
                </p.Stack>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__xnIay
                      )}
                    >
                      {"react-awesome-reveal"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__cqpI)}
                  title={"Reveal on scroll"}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__hvls9)}
                  >
                    <Reveal
                      data-plasmic-name={"reveal"}
                      data-plasmic-override={overrides.reveal}
                      cascade={true}
                      className={classNames("__wab_instance", sty.reveal)}
                      direction={"up" as const}
                      effect={"fade" as const}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__bsgZs
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__m4XRa
                          )}
                        >
                          {"JAY-Z"}
                        </div>
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.freeBox__ewP)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__agMyi
                          )}
                        >
                          {"FOLLOW ARTIST"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__uG3C6
                          )}
                        >
                          <a
                            className={classNames(
                              defaultcss.a,
                              sty.link__f09Jo
                            )}
                            href={"https://www.facebook.com/JayZ" as const}
                            target={"_blank" as const}
                          >
                            <IconIcon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__t3NPr
                              )}
                              role={"img"}
                            />
                          </a>

                          <a
                            className={classNames(
                              defaultcss.a,
                              sty.link__ylKik
                            )}
                            href={"https://twitter.com/sc?lang=en" as const}
                            target={"_blank" as const}
                          >
                            <Icon2Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__poEAd
                              )}
                              role={"img"}
                            />
                          </a>

                          <a
                            className={classNames(
                              defaultcss.a,
                              sty.link__ixz9B
                            )}
                            href={"https://lifeandtimes.com/" as const}
                            target={"_blank" as const}
                          >
                            <Icon3Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__wkP1
                              )}
                              role={"img"}
                            />
                          </a>
                        </p.Stack>
                      </p.Stack>
                    </Reveal>
                  </div>
                </ListItem>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__hJdNo
                      )}
                    >
                      {"react-parallax-tilt"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__eq3O)}
                  title={"3D parallax tilt effect"}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__s0OrA)}
                  >
                    <Tilt
                      data-plasmic-name={"tilt"}
                      data-plasmic-override={overrides.tilt}
                      className={classNames("__wab_instance", sty.tilt)}
                      reset={false}
                      tiltReverse={true}
                      trackOnWindow={false}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__gYvtA
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__jk5Wo,
                            hasVariant(globalVariants, "screen", "mobile")
                              ? ("inner-element" as const)
                              : ("inner-element" as const)
                          )}
                        />
                      </div>
                    </Tilt>
                  </div>
                </ListItem>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__bcZgl
                      )}
                    >
                      {"react-scroll-parallax"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__xtGnH)}
                  title={"Parallax scroll effect"}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__yeK4F)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__chzbw)}
                    >
                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax___0JtR5
                        )}
                        y={[-20, 20]}
                      >
                        <img
                          alt={"" as const}
                          className={classNames(defaultcss.img, sty.img__l6NM)}
                          loading={"lazy" as const}
                          src={image6BZy1EJvTxz8V}
                        />
                      </ParallaxWrapper>

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__jTmvk
                        )}
                        y={[40, -40]}
                      >
                        <img
                          alt={""}
                          className={classNames(defaultcss.img, sty.img___9Tt)}
                          loading={"lazy" as const}
                          src={image5YFsTPi6WzJiH}
                        />
                      </ParallaxWrapper>

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__j9X4U
                        )}
                        y={[-20, 20]}
                      >
                        <img
                          alt={""}
                          className={classNames(defaultcss.img, sty.img__k4TAj)}
                          loading={"lazy" as const}
                          src={image7Qebey7WcP8Ki}
                        />
                      </ParallaxWrapper>

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__k1Sfu
                        )}
                        y={[99, -99]}
                      >
                        <img
                          alt={""}
                          className={classNames(defaultcss.img, sty.img__dW3W3)}
                          loading={"lazy" as const}
                          src={image8OsNbT5LMrWcp}
                        />
                      </ParallaxWrapper>
                    </div>
                  </div>
                </ListItem>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__nr3Xc)}
                >
                  <ListItem
                    _package={null}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__gEYbw
                    )}
                    title={'A generic "Embed Code" component'}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__hae6J)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox___4Zri0
                        )}
                      >
                        <Embed
                          data-plasmic-name={"embed"}
                          data-plasmic-override={overrides.embed}
                          className={classNames("__wab_instance", sty.embed)}
                          code={
                            '<a class="twitter-timeline" href="https://twitter.com/plasmicapp?ref_src=twsrc%5Etfw">Tweets by plasmicapp</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>' as const
                          }
                        />
                      </div>
                    </p.Stack>
                  </ListItem>
                </p.Stack>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___7U7D6)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__yzT7H
                )}
              >
                {"How does this work?"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__h0L8B
                )}
              >
                <span className={"plasmic_default__all plasmic_default__span"}>
                  <React.Fragment>
                    {
                      "Plasmic is a page builder and design tool that has a kernel which "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontStyle: "italic" }}
                  >
                    {"runs from within your application"}
                  </span>
                  <React.Fragment>
                    {
                      '. We call the Plasmic project "hosted" by your application.'
                    }
                  </React.Fragment>
                </span>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___4ClIk
                )}
              >
                {
                  "This tight integration is what lets you easily and seamlessly expose code components of arbitrary complexity. They can connect to your application state, fetch data, implement complex behavior, and much more. All without bundling shenanigans."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___6M6D
                )}
              >
                {
                  "You can set the app host to be your localhost dev server (complete with hot reload working!) OR your actual production site."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___1FmI
                )}
              >
                <span className={"plasmic_default__all plasmic_default__span"}>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"What does it take to enable this for your codebase? "}
                  </span>
                  <React.Fragment>
                    {
                      "Simply add a snippet of code, and now you can configure any Plasmic project to use your application URL as the host. Then expose any component by calling registerComponent() on it. That's it!"
                    }
                  </React.Fragment>
                </span>
              </div>

              <a
                className={classNames(
                  defaultcss.a,
                  defaultcss.__wab_text,
                  sty.link__jRvAt
                )}
                href={
                  "https://docs.plasmic.app/learn/code-components/" as const
                }
                target={"_blank" as const}
              >
                {"See developer docs ->"}
              </a>

              <a
                className={classNames(
                  defaultcss.a,
                  defaultcss.__wab_text,
                  sty.link__zAE6
                )}
                href={"https://github.com/plasmicapp/code-components" as const}
                target={"_blank" as const}
              >
                {"See this project's host repo on GitHub ->"}
              </a>
            </p.Stack>

            <ColoredSection
              data-plasmic-name={"coloredSection"}
              data-plasmic-override={overrides.coloredSection}
              className={classNames("__wab_instance", sty.coloredSection)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___5F1Js)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__rjYPk
                  )}
                >
                  {
                    "Plasmic lets anyone build and deploy visual content—from full pages to sections of pages—within any tech stack."
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__iSYk4
                  )}
                >
                  {
                    "Plasmic powers some of the largest websites in the world. Companies from boutique brands to Fortune 500s use Plasmic to eliminate swaths of development work and let marketing and design teams iterate incredibly fast."
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__gravk
                  )}
                >
                  {
                    "And now with code components, developers can equip their whole team with the exact right set of building blocks to move even faster."
                  }
                </div>

                <LinkButton
                  data-plasmic-name={"linkButton"}
                  data-plasmic-override={overrides.linkButton}
                  className={classNames("__wab_instance", sty.linkButton)}
                  href={"https://studio.plasmic.app/signup" as const}
                  icon={
                    <Icon8Icon
                      className={classNames(defaultcss.all, sty.svg___9KvQ)}
                      role={"img"}
                    />
                  }
                  label={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__w0NQi
                      )}
                    >
                      {"Try Plasmic for free"}
                    </div>
                  }
                  type={["white", "rightIcon"]}
                />

                <div
                  className={classNames(defaultcss.all, sty.freeBox__t8GM)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__y5Bw5
                  )}
                >
                  {
                    "Code components are just the beginning of what application hosting unlocks."
                  }
                </div>

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(defaultcss.a, sty.link__x8Tbo)}
                  href={"https://twitter.com/plasmicapp" as const}
                  target={"_blank" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__kFhWk
                    )}
                  >
                    {"Follow @plasmicapp on Twitter to see what's next."}
                  </div>
                </p.Stack>

                <a
                  className={classNames(defaultcss.a, sty.link__oKWzs)}
                  href={"https://www.plasmic.app" as const}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___4JXgo)}
                    loading={"lazy" as const}
                    src={image14Zxn1TasF4EtG}
                  />
                </a>
              </p.Stack>
            </ColoredSection>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionHeading",
    "columns",
    "arwesCard",
    "h1",
    "arwesFigure",
    "cmsGallery",
    "reveal",
    "tilt",
    "embed",
    "coloredSection",
    "linkButton"
  ],
  sectionHeading: ["sectionHeading"],
  columns: ["columns"],
  arwesCard: ["arwesCard", "h1", "arwesFigure"],
  h1: ["h1"],
  arwesFigure: ["arwesFigure"],
  cmsGallery: ["cmsGallery"],
  reveal: ["reveal"],
  tilt: ["tilt"],
  embed: ["embed"],
  coloredSection: ["coloredSection", "linkButton"],
  linkButton: ["linkButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  sectionHeading: typeof SectionHeading;
  columns: typeof Columns;
  arwesCard: typeof ArwesCard;
  h1: "h1";
  arwesFigure: typeof Figure;
  cmsGallery: typeof CmsGallery;
  reveal: typeof Reveal;
  tilt: typeof Tilt;
  embed: typeof Embed;
  coloredSection: typeof ColoredSection;
  linkButton: typeof LinkButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionHeading: makeNodeComponent("sectionHeading"),
    columns: makeNodeComponent("columns"),
    arwesCard: makeNodeComponent("arwesCard"),
    h1: makeNodeComponent("h1"),
    arwesFigure: makeNodeComponent("arwesFigure"),
    cmsGallery: makeNodeComponent("cmsGallery"),
    reveal: makeNodeComponent("reveal"),
    tilt: makeNodeComponent("tilt"),
    embed: makeNodeComponent("embed"),
    coloredSection: makeNodeComponent("coloredSection"),
    linkButton: makeNodeComponent("linkButton"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
