// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iX1qkSjgNN2uqWdAcYpiJf
// Component: 9J-zjImHs6Nv
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ListItem from "../../ListItem"; // plasmic-import: -oP-bZni7oo/component
import YouTube from ""; // plasmic-import: xdkygkmsYFc/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_code_component_examples.module.css"; // plasmic-import: iX1qkSjgNN2uqWdAcYpiJf/projectcss
import * as sty from "./PlasmicExampleSection.module.css"; // plasmic-import: 9J-zjImHs6Nv/css

export type PlasmicExampleSection__VariantMembers = {};

export type PlasmicExampleSection__VariantsArgs = {};
type VariantPropType = keyof PlasmicExampleSection__VariantsArgs;
export const PlasmicExampleSection__VariantProps = new Array<VariantPropType>();

export type PlasmicExampleSection__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicExampleSection__ArgsType;
export const PlasmicExampleSection__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicExampleSection__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultExampleSectionProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicExampleSection__RenderFunc(props: {
  variants: PlasmicExampleSection__VariantsArgs;
  args: PlasmicExampleSection__ArgsType;
  overrides: PlasmicExampleSection__OverridesType;
  dataFetches?: PlasmicExampleSection__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Use off-the-shelf components.",
        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}

      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <ListItem
              _package={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__rriYn
                  )}
                >
                  {"react-youtube"}
                </div>
              }
              className={classNames("__wab_instance", sty.listItem__dByAj)}
              title={"Youtube"}
            >
              <YouTube
                className={classNames("__wab_instance", sty.youTube___4IMzt)}
                videoId={"R6MeLqRQzYw" as const}
              />
            </ListItem>
          ),

          value: args.slot
        })}
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicExampleSection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicExampleSection__VariantsArgs;
    args?: PlasmicExampleSection__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicExampleSection__Fetches;
  } & Omit<PlasmicExampleSection__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicExampleSection__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicExampleSection__ArgProps,
      internalVariantPropNames: PlasmicExampleSection__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicExampleSection__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicExampleSection";
  } else {
    func.displayName = `PlasmicExampleSection.${nodeName}`;
  }
  return func;
}

export const PlasmicExampleSection = Object.assign(
  // Top-level PlasmicExampleSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicExampleSection
    internalVariantProps: PlasmicExampleSection__VariantProps,
    internalArgProps: PlasmicExampleSection__ArgProps
  }
);

export default PlasmicExampleSection;
/* prettier-ignore-end */
