// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: fJogwOTVlCE
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Testimonial from "../../Testimonial"; // plasmic-import: E_l1hqcHcA/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicTestimonialsTop.module.css"; // plasmic-import: fJogwOTVlCE/css

import image17U7CGaQy from "./images/image17.png"; // plasmic-import: U_7c_gaQy/picture
import image41PGoZZ6Ey from "./images/image41.png"; // plasmic-import: pGoZ-z6Ey/picture
import image39Y1CLdtC5P from "./images/image39.png"; // plasmic-import: Y1cLdtC5p/picture
import image19TueIhGKhL from "./images/image19.png"; // plasmic-import: tueIhGKhL/picture
import image18VvWfewPgF from "./images/image18.png"; // plasmic-import: VvWfewPgF/picture
import image49S6UJdcNii from "./images/image49.png"; // plasmic-import: S6uJdcNII/picture
import image58CTc2ZXwO from "./images/image58.png"; // plasmic-import: CTc2zXw-o/picture
import image45CZnS6ZLBf from "./images/image45.png"; // plasmic-import: cZnS6zLBf/picture
import image32RtBuhLfpe from "./images/image32.png"; // plasmic-import: RtBuhLfpe/picture
import image26G5JsDdQkx from "./images/image26.png"; // plasmic-import: G5jsDdQkx/picture
import image301QXLsp3Gl from "./images/image30.png"; // plasmic-import: 1qXLsp3Gl/picture
import image88Ijfr7QQeh from "./images/image88.png"; // plasmic-import: ijfr7qQeh/picture
import image57AVfwvYtpk from "./images/image57.png"; // plasmic-import: AVfwvYTPK/picture
import image52WV9THJz5J from "./images/image52.png"; // plasmic-import: wV9tHJz5J/picture
import image21Dqmr3K45D from "./images/image21.png"; // plasmic-import: Dqmr3K45D/picture

export type PlasmicTestimonialsTop__VariantMembers = {};

export type PlasmicTestimonialsTop__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestimonialsTop__VariantsArgs;
export const PlasmicTestimonialsTop__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTestimonialsTop__ArgsType = {};
type ArgPropType = keyof PlasmicTestimonialsTop__ArgsType;
export const PlasmicTestimonialsTop__ArgProps = new Array<ArgPropType>();

export type PlasmicTestimonialsTop__OverridesType = {
  root?: p.Flex<"section">;
};

export interface DefaultTestimonialsTopProps {
  className?: string;
}

function PlasmicTestimonialsTop__RenderFunc(props: {
  variants: PlasmicTestimonialsTop__VariantsArgs;
  args: PlasmicTestimonialsTop__ArgsType;
  overrides: PlasmicTestimonialsTop__OverridesType;
  dataFetches?: PlasmicTestimonialsTop__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"section"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox__vYqM8)}
      >
        <Testimonial
          company={"Intuit"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__yRbUr
              )}
            >
              {"James Armenta"}
            </div>
          }
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__jgTuv
              )}
            >
              {
                "It’s already been a huge increase in efficiency for me, personally. I’m really looking forward to a huge drop in scope for our tests that require new components (most of them)."
              }
            </div>
          }
          title={"Software Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___0ADPi)}
            loading={"lazy" as const}
            src={image17U7CGaQy}
          />
        </Testimonial>

        {false ? (
          <Testimonial
            company={"Field Office"}
            name={
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__mLKsP
                )}
              >
                {"Jean-Philippe Lauzon"}
              </div>
            }
            noLink={"noLink" as const}
            quote={
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__o32Fv
                )}
              >
                {
                  "Simply wanted to state how impress I was with what you guys came up with. At Field Office, we've been trying to get ahead of the competition through efficiency, blazing-fast site, and outstanding design and I strongly believe your product will be of great help to move us forward in that direction."
                }
              </div>
            }
            title={"Founding Partner"}
          >
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__fDqIo)}
              loading={"lazy" as const}
              src={image41PGoZZ6Ey}
            />
          </Testimonial>
        ) : null}

        <Testimonial
          company={"Venturemark"}
          dest={"https://www.producthunt.com/posts/plasmic" as const}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___0Az3O
              )}
            >
              {"Marcus Ellison"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___7SgFl
              )}
            >
              {
                "Our designer is empowered to instrument pixel perfect, responsive design. And frontend developers can focus less on boilerplate code. From design -> code -> deploy only takes minutes. And the design is pixel perfect. We're now using Plasmic for our entire web app in production."
              }
            </div>
          }
          title={"CEO"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__tanYt)}
            loading={"lazy" as const}
            src={image39Y1CLdtC5P}
          />
        </Testimonial>

        <Testimonial
          company={"Github"}
          dest={
            "https://twitter.com/colebemis/status/1283913672851517440" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__k3VRg
              )}
            >
              {"Cole Bemis"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__cuf0D
              )}
            >
              {
                "I had the opportunity to test out an early version of Plasmic and it’s awesome! Excited for the future of this design tool "
              }
            </div>
          }
          title={"Design Systems Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___6TPp)}
            loading={"lazy" as const}
            src={image19TueIhGKhL}
          />
        </Testimonial>

        <Testimonial
          company={"Intrepid Ventures"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__qu1CY
              )}
            >
              {"Collin Thompson"}
            </div>
          }
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__dQdnH
              )}
            >
              {
                "By far one of the most empowering tools to come out in a while. Week by week it keeps getting better. If you’re a designer/no coder/visual developer who wants to make world class applications, or a design or development studio looking for a way to serve your clients better and faster—I highly recommend checking out Plasmic."
              }
            </div>
          }
          title={"CEO"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__x76Bi)}
            loading={"lazy" as const}
            src={image18VvWfewPgF}
          />
        </Testimonial>

        <Testimonial
          company={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__nSDn2
              )}
            >
              {"Coinbase"}
            </div>
          }
          dest={
            "https://twitter.com/frankyoo/status/1283963068003700739" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___4MWou
              )}
            >
              {"Frank Yoo"}
            </div>
          }
          quote={
            "One step closer to the holy grail of design tools + the benefit of more productive teams. Excited about this milestone."
          }
          title={"VP of Design & Research"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__y9UQa)}
            loading={"lazy" as const}
            src={image49S6UJdcNii}
          />
        </Testimonial>

        <Testimonial
          company={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__z9Uk3
              )}
            >
              {"Supersorted.app"}
            </div>
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__a2Nyt
              )}
            >
              {"Nitin Aggarwal"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__uAgt1
              )}
            >
              {
                "We're totally blown away many times a day because of plasmic. You're doing god's work."
              }
            </div>
          }
          title={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__z8Gns
              )}
            >
              {"Founder"}
            </div>
          }
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__imsLn)}
            loading={"lazy" as const}
            src={image58CTc2ZXwO}
          />
        </Testimonial>

        <Testimonial
          company={"Capital Rx"}
          dest={
            "https://twitter.com/thoughtntheory/status/1288567547739148288" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__z3KbR
              )}
            >
              {"Dennis Eusebio"}
            </div>
          }
          quote={
            "Trying out @plasmicapp. Tons of potential here. If you’re building a design system for your team I’d suggest giving it a look."
          }
          title={"Director of UI/UX"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__fGbTy)}
            loading={"lazy" as const}
            src={image45CZnS6ZLBf}
          />
        </Testimonial>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox___7R1F)}
      >
        <Testimonial
          company={"APS Physics"}
          name={"Justin Wilkerson"}
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__xB7Ir
              )}
            >
              <span className={"plasmic_default__all plasmic_default__span"}>
                <React.Fragment>
                  {"I was pleasantly surprised and at times, "}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"blown away"}
                </span>
                <React.Fragment>
                  {
                    ", with the Plasmic approach to solving the problem. The whole concept of variants, interactive variants, and slots feels natural and intuitive."
                  }
                </React.Fragment>
              </span>
            </div>
          }
          title={"Software Developer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__ycmiJ)}
            loading={"lazy" as const}
            src={image32RtBuhLfpe}
          />
        </Testimonial>

        <Testimonial
          company={"Facebook"}
          dest={"https://twitter.com/_dte/status/1283859788372287491" as const}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___7R7Vv
              )}
            >
              {"Dan Eden"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___3QsaT
              )}
            >
              {
                "I was honored to get a preview of @plasmicapp around a year ago and… wow. The progress they’ve made to bridge design & development using (and generating!) real components is super exciting."
              }
            </div>
          }
          title={"Design Systems Lead"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__hhzy4)}
            loading={"lazy" as const}
            src={image26G5JsDdQkx}
          />
        </Testimonial>

        <Testimonial
          company={"Zapier"}
          dest={
            "https://twitter.com/the_real_stacie/status/1303853467845292033" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__p94WW
              )}
            >
              {"Stacie Taylor"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__c82Z6
              )}
            >
              {
                "Watching @yaaang demo quickly creating #react components with ease using his app @plasmicapp for the second time tonight at a @_collab_lab exclusive presentation. AND I’m just as blown away as I was last time! Check out this app, y’all!"
              }
            </div>
          }
          title={"Frontend Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__blaMx)}
            loading={"lazy" as const}
            src={image301QXLsp3Gl}
          />
        </Testimonial>

        <Testimonial
          company={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__pSmQn
              )}
            >
              {"8020"}
            </div>
          }
          dest={
            "https://twitter.com/Tony_DesignTest/status/1381200086596784131" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__f0T81
              )}
            >
              {"Matt Varughese"}
            </div>
          }
          quote={
            "I'm super surprised more folks aren't talking about @plasmicapp — I just got a demo and it's awesome. \n\nIt's like Figma and Webflow had a baby that outputs React code."
          }
          title={"Partner"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__vvVCe)}
            loading={"lazy" as const}
            src={image88Ijfr7QQeh}
          />
        </Testimonial>

        <Testimonial
          company={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__emjwk
              )}
            >
              {"Coupa Software"}
            </div>
          }
          dest={
            "https://twitter.com/Tony_DesignTest/status/1381200086596784131" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__dp2Nt
              )}
            >
              {"Tony Key"}
            </div>
          }
          quote={
            "Plasmicapp is the most important app to be released in the last five years."
          }
          title={"Senior UX Designer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__hZlk3)}
            loading={"lazy" as const}
            src={image57AVfwvYtpk}
          />
        </Testimonial>

        <Testimonial
          company={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__m3CNo
              )}
            >
              {"Andreessen Horowitz"}
            </div>
          }
          dest={
            "https://twitter.com/stevesi/status/1283833356396851201" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__n5FX
              )}
            >
              {"Steve Sinofsky"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___0J1XG
              )}
            >
              {"Exciting work going on at Plasmic."}
            </div>
          }
          title={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___8AVni
              )}
            >
              {"Board Partner"}
            </div>
          }
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___6Ryqy)}
            loading={"lazy" as const}
            src={image52WV9THJz5J}
          />
        </Testimonial>

        <Testimonial
          company={"Microsoft"}
          dest={
            "https://twitter.com/monirabuhilal/status/1283932117823623169" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__sjhnU
              )}
            >
              {"Monir Abu Hilal"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__j3NP
              )}
            >
              {
                "So exciting to see Plasmic announced publicly and the progress the team has made so far!\n\nA new design tool that bridges dev & design by allowing designers+engineers to create or compose existing react components visually and generate production-ready react code!"
              }
            </div>
          }
          title={"Principal Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__vvVdY)}
            loading={"lazy" as const}
            src={image21Dqmr3K45D}
          />
        </Testimonial>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestimonialsTop__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestimonialsTop__VariantsArgs;
    args?: PlasmicTestimonialsTop__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTestimonialsTop__Fetches;
  } & Omit<PlasmicTestimonialsTop__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTestimonialsTop__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestimonialsTop__ArgProps,
      internalVariantPropNames: PlasmicTestimonialsTop__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTestimonialsTop__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestimonialsTop";
  } else {
    func.displayName = `PlasmicTestimonialsTop.${nodeName}`;
  }
  return func;
}

export const PlasmicTestimonialsTop = Object.assign(
  // Top-level PlasmicTestimonialsTop renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTestimonialsTop
    internalVariantProps: PlasmicTestimonialsTop__VariantProps,
    internalArgProps: PlasmicTestimonialsTop__ArgProps
  }
);

export default PlasmicTestimonialsTop;
/* prettier-ignore-end */
